simplify the code
join two if constructs into one.

diff --git a/selkie b/selkie
--- a/selkie
+++ b/selkie
@@ -117,13 +117,11 @@ if [ ! "$username" ]; then
 fi
 
 if [ $set ]; then
-	if [ $(echo $get_contents | wc -c) != 1 ]; then
-		if [ ! $force ]; then
-			echo "error:  entry with the name $name and username"\
-				"$username already exists."
-			echo "to overwrite the entry, provide the '-f' option."
-			exit 1
-		fi
+	if [ $(echo $get_contents | wc -c) != 1 ] && [ ! $force ]; then
+		echo "error:  entry with the name $name and username"\
+			"$username already exists."
+		echo "to overwrite the entry, provide the '-f' option."
+		exit 1
 	fi
 	[ ! "$password" ] && password=$(openssl rand -base64 50 | tr -d '=+/\n')
 	updated_contents=$(echo "$all_entries" | sed "/$sed_search/d")
@@ -132,7 +130,7 @@ if [ $set ]; then
 	updated_contents="$updated_contents\n$new_entry"
 	echo "$updated_contents" |
 		openssl enc -aes-256-cbc -k "$key" -out "$SELKIE_STORAGE"
-	exit
+			exit
 fi
 
 if [ $remove ]; then
